### ISSUE TITLE
occasionally server sends "fragmented" acks

### ISSUE THREAD

**Issue by gfarrell** [mcollina/node-coap#140]
This is quite hard to describe, and I'm struggling to reproduce it, but I'm fairly sure the source of the error can't be my application code.

The setup:
We have devices on a 6lowpan mesh in the field, connected to a gateway, which bridges the network via a VPN to our app servers. The devices send data via CoAP, and expect an acknowledgment with code `2.04` if the data were accepted. Only then does the packet get removed from the sending queue.

What I'm seeing:
About 75% of the time, when using `tshark` to examine the CoAP traffic via `sudo tshark -i tap0 -f "udp port 5683"`, I see:

```
3   4 109.044848 ec92::212:4b00:ea3:2035 -> bbbb::4001   CoAP 129 CON, TID:5483, PUT
4   5 109.091931   bbbb::4001 -> ec92::212:4b00:ea3:2035 CoAP 66 ACK, TID:5483, 2.04 Changed
```

Which is exactly as expected. About 25% of the time, I get this:

```
15  16 207.080173 ec92::212:4b00:ea3:2035 -> bbbb::4001   CoAP 129 CON, TID:5486, PUT
 17 207.142914   bbbb::4001 -> ec92::212:4b00:ea3:2035 CoAP 66 ACK, TID:5486, Empty Message
 18 207.152959   bbbb::4001 -> ec92::212:4b00:ea3:2035 CoAP 66 CON, TID:64217, 2.04 Changed
18  19 209.365676   bbbb::4001 -> ec92::212:4b00:ea3:2035 CoAP 66 CON, TID:64217, 2.04 Changed
19  20 213.797643   bbbb::4001 -> ec92::212:4b00:ea3:2035 CoAP 66 CON, TID:64217, 2.04 Changed
20  21 222.660820   bbbb::4001 -> ec92::212:4b00:ea3:2035 CoAP 66 CON, TID:64217, 2.04 Changed
```

Things to notice:

(1) the initial response is an "empty message", but subsequently a load of `2.04`s do get sent
(2) my guess is that the reason the messages are repeated is a combination of link-layer retries and application-layer retries (if one examines the timing over a longer period this becomes quite clear).
(3) the message id (TID, here, instead of MID for some reason) is different for the original "broken" ack, and the subsequent "fixed" acks (`5486`, `64217`).

Unfortunately, in my local setup this has been impossible to replicate so far and I am unable to attach a debugger to my production server.

My guess is that somewhere in the `node-coap` library (or its dependencies) the response is being sent despite it not yet having been sent by my application code.

I'm node terribly aux fait with the `node-coap` codebase, so I'm not sure where this might be happening.

**Comment by mcollina** [comment]
@gfarrell unfortunately I am in no position to help you, because #97. If you would like to send a PR to address this bug, I would be happy to review it.

**Comment by gfarrell** [comment]
Ok, progress! I am pretty sure that there's some sort of timeout in the `node-coap` library (or deps). On my local machine, I delayed my `ack`ing by 1s just to see what would happen, and lo-and-behold I get the same result.

![image](https://cloud.githubusercontent.com/assets/314331/23309979/ad7e723a-faa8-11e6-85e6-44c1b4efcdaa.png)

**Comment by gfarrell** [comment]
@mcollina would you have any idea where to look?

**Comment by GiedriusM** [comment]
@gfarrell Correct me if I misunderstand this: in the second capture frame 15 is good, but frame 17 should be an ACK with 2.04 code and frames 18 and onward are garbage? Could you also upload the pcap file somewhere?

**Comment by gfarrell** [comment]
@GiedriusM yes, that's correct. Frames 18 onwards seem to be what frame 17 *should* be, but for some reason it's getting garbled.

**Comment by gfarrell** [comment]
I'll get a pcap now from my local test

**Comment by gfarrell** [comment]
[pcap.tar.gz](https://github.com/mcollina/node-coap/files/799832/pcap.tar.gz)

**Comment by GiedriusM** [comment]
Do you have a code that reproduces it?

**Comment by gfarrell** [comment]
Have a meeting now, but can write a fairly trivial MVE which should reproduce the problem

**Comment by gfarrell** [comment]
@GiedriusM here's an MVE which exactly replicates the problem for me:

```javascript
"use strict";

const coap = require("coap");

const port = 9084;
const server = coap.createServer({ type: "udp6" });

server.on("request", (req, res) => {
    console.log("got a request :)");
    setTimeout(() => {
        res.code = 204;
        res.end();
    }, 1000);
});

server.listen(port);

console.log(`server listening on ${port}`);

process.on("exit", () => {
    console.log("exiting...");
    server.close();
});
```

When I try to then use the [CoAP cli tool](https://github.com/mcollina/coap-cli):

```
coap put coap://[::1]:9084/data -p "1485182391,temp,99"
```

I see the following output in wireshark:
![wireshark](https://cloud.githubusercontent.com/assets/314331/23315084/9e62274c-fabc-11e6-8833-758c64bde6d9.png)

[pcap file](https://github.com/mcollina/node-coap/files/800118/mve_pcap.pcapng.gz)

**Comment by GiedriusM** [comment]
@gfarrell the quick workaround for you is to increase the auto-ACK timeout
```javascript
const server = coap.createServer({piggybackReplyMs: 1500, type: "udp6" });
```

The problem itself is a bit more complicated. In short, this happens when response is delayed more than piggybackReplyMs, but the reason for this are two bugs:
1) Auto-ACK does not add Token option and so auto-ack frame on the client side may be ignored.
2) After auto-ACK triggers, the response object is mangled/pseudo-deleted (see outgoing_message.js:[34-44]) and so when the late .end() call finally arrives, it sends a corrupted response frame.
Also, as a semi-related bug:
3) I noticed that if I disable auto-ACK and delay .end() call for several seconds, so that the client retry triggers, server gets a duplicate request event. IMO this should not happen, i.e. the server LRU cache should contain requests, rather than responses and if a duplicate arrives, send a response if and only if the original response end()'ed.

@mcollina, I have few questions for you. First, do you recollect why that response altering (mentioned in bug 2) was done? Personally, I would remove some of that code, but I'm afraid it may be there for a reason (name piggybackReplyMs suggests somewhat different functionality than autoAcknowledgement). Also, why does auto-ACK use raw send instead of trigering end() call. I'm thinking of adding an option to disable auto-ACK altogether, by using piggybackReplyMs parameter (None or <=0), so that the user would have an option to not send any reply, unless end() is called explicitly.

**Comment by gfarrell** [comment]
@GiedriusM thanks, that patch works for the MVE above. I'll add it to our application for now. Could this be partially related to #138 (for which I intend to submit a PR when I get a moment)?

**Comment by GiedriusM** [comment]
@gfarrell At first I thought so too, but they're separate problems. In #138 calling `end()` multiple times sends multiple identical responses. Here, however, the auto-`end()` actually changes/corrupts the response and so the next time `end()` is called you get entirely different type of message going out.
