### ISSUE TITLE
Server detect observe client closed.

### ISSUE THREAD

**Issue by benjamin658** [mcollina/node-coap#152]
Hi, I'm trying to implement CoAP observe client and server, the server's 'finish' event will be triggered if I call res.end() on the server side, but if I close the client directly (use control + C), server won't trigger any event.

Is there any way to know the observe client is closed by any reason (Internet fail,  close manually...) on the server side? 

Thanks a lot!

**Comment by GiedriusM** [comment]
First, lets make sure that we use the same terms. In CoAP Observe context, the client sends observe request to the server and if the request is successful, the server will start sending observe notifications/messages to the client.

In case the client doesn't want to receive the notifications it can send observe request with observe option value 1, which cancels the observation OR it can also send a CoAP RESET message. In either of the cases the server must stop sending the notifications. 

In case the client is unexpectedly closed: 
a) the server will keep sending UNCONFIRMABLE notifications until the client  comes back online again and sends a RESET due to unknown state/message id.
b) the server will send CONFIRMABLE notifications and if no acknowledgment is received - it will cancel the notifications

In case the server is closed, there's no requirement to inform the client. In [RFC7641](https://tools.ietf.org/html/rfc7641#section-4) is stated that if the server can't send any notifcations it SHOULD send a notification with 4.06 code. However, I would argue that's not the same as the server shutting down.

In practice it is application specific how it want's to handle the server shutdown. It could add a timeout on the notifications or have a periodic check on the resources availability.

Does this answer your question or am I misunderstanding it?

**Comment by benjamin658** [comment]
Hi @GiedriusM , thanks for your reply!

I found that if the client is unexpectedly closed, res.on('finish') callback won't triggered immediately, but after about two minutes, the callback will be trigger as expected.

**Comment by GiedriusM** [comment]
@benjamin658, could you provide an example code?

**Comment by HobaiRiku** [comment]
@GiedriusM same situation ,when client is unexpectedly closed,  'finish' will triggered after many time of  "con" sent from server  ,example code is the 'observe_client.js' and 'observe_server' in examples
<img width="1125" alt="2018-03-22 2 47 15" src="https://user-images.githubusercontent.com/26238803/37755314-fb45845c-2ddf-11e8-923a-10d4129205f9.png">
