### ISSUE TITLE
Support for ipv6 scope id

### ISSUE THREAD

**Issue by MarcCircosta** [mcollina/node-coap#334]
I wonder, is there a way to use this library with an ipv6 link local address, with the scope id included? I have an embedded device on my ppp0 interface that I'm trying to connect to, but get this:

input: 'coap://[fe80::0011:2233:3200:0001%ppp0]:12345/RCI',
code: 'ERR_INVALID_URL'

Any suggestions are welcome, thanks.

**Comment by JKRhb** [comment]
Hi @MarcCircosta! While the error you got is probably a parsing error, the research I did so far indicates that you cannot specify the interface ID in an IP address due to Node.js :/ https://github.com/nodejs/help/issues/2073#issuecomment-515728635 Have you found any other information in this regard?

**Comment by MarcCircosta** [comment]
Hi Jan, thanks for your quick response. I agree, it seems it would require some hacking at, and isn't a great option. I think a better solution is have my embedded device advertise via mDNS. I'll probably focus my efforts there. Thanks for your help.
