### ISSUE TITLE
can token len be less than 8

### ISSUE THREAD

**Issue by Thousif-khan** [mcollina/node-coap#335]
can we set the token length?

**Comment by JKRhb** [comment]
You mean in requests? The token length should vary between 1 and 8 bytes at the moment, being randomly determined when a new request is sent.

**Comment by Thousif-khan** [comment]
is it possible to set token length in the request?, In my request i see the token length is fixed at 8.

**Comment by JKRhb** [comment]
> In my request i see the token length is fixed at 8.

Oh, you are right, this is caused by the behavior of this method:

https://github.com/mcollina/node-coap/blob/4c9591a92c76bb5a178d5e22c73440c90e9c630b/lib/agent.ts#L367-L378

> is it possible to set token length in the request?

I am afraid, you can only set a custom token at the moment (using the `token` parameter when creating a request):

https://github.com/mcollina/node-coap/blob/4c9591a92c76bb5a178d5e22c73440c90e9c630b/models/models.ts#L100

So you could implement your own token generation function and then pass the generated token to the request. What you describe is definitely a missing feature, though, also considering that you could also use an extended token length (as described in [RFC 8974](https://datatracker.ietf.org/doc/html/rfc8974)). I guess it would be useful to be able to set it as a config parameter.

**Comment by Thousif-khan** [comment]
thanks. will go with custom token parameter.
