### ISSUE TITLE
Blockwise support dont work with pipe()

### ISSUE THREAD

**Issue by dario1985** [mcollina/node-coap#82]
Look like the blockwise support (Block2 option) is implemented in OutMessage.end(), so when the end() is called without payload (or when stream end) is skipped and the OutoingMessage.end() is called instead, so a 'Max packet size is 1280: current is XXX" error is thrown.

<pre>
coapServer.on('request', function router(request, response) {
  ...
  largestream.pipe(response)
  ...
}
</pre>

a workaround we found is collect the buffer outside:

<pre>
coapServer.on('request', function router(request, response) {
  ...
  largestream.pipe(bl(function (err, data) {
    response.end(data)
  }))
  ...
}
</pre>

**Comment by mcollina** [comment]
Hey @dario1985! Would you mind sending a PR to address this issue?

**Comment by seppestas** [comment]
I looked into this issue a bit and found it non-trivial to achieve the expected behaviour with the current interface of this library.

In order to support the Block2 request option, the paypload is cached and `OutMessage.end()` automatically sends the correct slice of the payload. For this approach to work,  the entire message needs to be stored in memory.

In order to support streaming responses, the interface of this library could be adapted to include the block size and block number in the request, moving responsibility of sending the correct payload  section from the library to the consumer of the library.

An other option could be to use some form of file-based interface that allows this library to access a specific section of the payload using some form of `seek` function. This could be implemented in a streaming way. 

IMO, seeing the typical use case of constrained devices, and thus typically fairly small data sizes, it might make more sense to just remove the streaming interface in favor of the simpler interface.

I would definitely remove the streaming interface of the server response to address the confusing behaviour.

@mcollina What do you think? Would it make sense to overhaul the interface of this library to support streaming responses?
